### ISSUE TITLE
[APP] Не вызывается скрипт создания структуры БД

### ISSUE THREAD

**Issue by anry-das** [Viencer/Hospital#6]
Скрипт нужно вызывать только при условии, что в БД еще нет таких таблиц.
Проверить наличие таблиц можно запросом
`select count(1) as cnt from user_table where table_name like 'LAB3MU%';`
(если cnt == 0, то вызывам скрипт создания)
Сейчас вызывается безусловно, т.е. при каждом запуске будет пытаться создать структуру, и при наличии таблиц - будут ошибки (как минимум) или аварийное завершение.

**Comment by Viencer** [comment]
commit 6ae496c0f26d4aa1e91de9a059f41ca53429e284
