### ISSUE TITLE
[REFACTOR] DaoConnectionImpl

### ISSUE THREAD

**Issue by anry-das** [Viencer/Hospital#7]
Содержимое не соответствует названию.
Судя по названию класса, в нем д.б. все, что связано с подключением к БД. Здесь же собраны все методы работы с БД, что не совсем правильно.
Этот класс нужно разбить на несколько. Например, согласно интерфесам в пакете dao.

**Comment by Viencer** [comment]
commit 6cc245af253cd2add8192b7daedb5102a1c09aec
